---
- name: Create Cloud Infra
  hosts: localhost
  gather_facts: no
  vars:
    infra_provider: undef
    aws_public_key: undef
  tasks:
  - include_role:
      name: "demo.cloud.{{ infra_provider }}"
      tasks_from: create_infra
