---
azure_provision_vm:
  author: "David Rojas"
  readme: "https://github.com/ansible/product-demos/blob/master/docs/infrastructure/azure_provision_vm.md"
  category: infrastructure
  name: "INFRASTRUCTURE / Azure Provision VM"
  description: "Provision RHEL VM on Azure with Ansible Tower Survey and Environmental variables"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/azure_provision_vm.yml"
  credential: "azure_credential"
  survey_enabled: true
  survey_spec:
    name: Azure Provision VM
    description: Provisioning a RHEL VM with Tower?
    spec:
      - type: text
        question_name: Enter name of your resource group
        question_description: This can be an existing or new resource group
        variable: resource_group
        required: true
        #default: 
        
      - type: multiplechoice
        question_name: What Azure region do you want to host your VM
        question_description: Select one from the drop-down
        variable: location
        required: true
        default: eastus 
        choices:
          - eastus
          - eastus2   
          - westus
          - centralus

      - type: text
        question_name: Enter the name of the VM
        question_description: You can't use any special characters or whitesapces
        variable: vm_name
        required: true
        #default:
  #video: "https://www.youtube.com/watch?v=pU8ZgSBuEJw&list=PLdu06OJoEf2bp-PNtxPP_2n7Avkax8TED"
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - windows
    - demo
