---
chocolatey_features:
  author: "David Rojas"
  readme: "https://github.com/ansible/product-demos/blob/master/docs/infrastructure/chocolatey_features.md"
  category: infrastructure
  name: "INFRASTRUCTURE / Chocolatey Features Config"
  description: "Enable or disable various Chocolatey features"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/chocolatey_features.yml"
  credential: "Workshop Credential"
  survey_enabled: true
  survey_spec:
    name: Chocolatey Features Config
    description: Which feature do you want to select?
    spec:
      - type: multiplechoice
        question_name: Select the feature you would like to enable or disable?
        question_description: Select one from the drop-down list
        variable: feature
        required: true
        #default: 
        choices:
          - checksumFiles
          - stopOnFirstPackageFailure
          - autoUninstaller
          - virusCheck
      - type: multiplechoice
        question_name: What state do you want the feature in?
        question_description: Select enabled or disabled
        variable: state
        required: true
        default: enabled
        choices:
          - enabled
          - disabled
  #video: "https://www.youtube.com/watch?v=pU8ZgSBuEJw&list=PLdu06OJoEf2bp-PNtxPP_2n7Avkax8TED"
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - windows
    - demo
