---
chocolatey_config:
  author: "David Rojas"
  readme: "https://github.com/ansible/product-demos/blob/master/docs/infrastructure/chocolatey_config.md"
  category: infrastructure
  name: "INFRASTRUCTURE / Chocolatey Config"
  description: "Configure Chocolatey parameters that require not just enabling but adding values"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/chocolatey_config.yml"
  credential: "Workshop Credential"
  survey_enabled: true
  survey_spec:
    name: Chocolatey Config
    description: Select a chocolatey parameter and config the value for it
    spec:
      - type: multiplechoice
        question_name: Select the parameter you would like to add change or remove
        question_description: Select one from drop-down
        variable: config_item
        required: true
        #default: 
        choices:
          - proxyUser
          - commandExecutionTimeoutSeconds
          - cacheLocation
      - type: multiplechoice
        question_name: Do you want to enable or disable this parameter?
        question_description: Select Present or Absent
        variable: state
        required: true
        default: present 
        choices:
          - present
          - absent  
      - type: text
        question_name: Enter the value for the parameter
        question_description: This is free form as each parameter has different values. Leave blank when setting as "absent"
        variable: value
        required: false
        #default:  
           
  #video: "https://www.youtube.com/watch?v=pU8ZgSBuEJw&list=PLdu06OJoEf2bp-PNtxPP_2n7Avkax8TED"
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/davidrojas25/product-demos"
  workshop_type:
    - windows
    - demo
