---
- name: install chocolatey package on Windows host
  hosts: windows

  vars:
    choco_packages: git
    app_state: present

  collections:
    - chocolatey.chocolatey  

  tasks:

    - name: Install multiple packages
      win_chocolatey:
        name: "{{ choco_packages }}"
        state: "{{ app_state }}"