---
- name: enabling or disabling chocolatey features
  hosts: windows

  vars:
    feature: stopOnFirstPackageFailure
    state: enabled

  collections:
    - chocolatey.chocolatey  

  tasks:

    - name: enable or disable Chocolatey features
      win_chocolatey_feature:
        name: "{{ feature }}"
        state: "{{ state }}"