---
- name: turn off community-grid
  hosts: "{{ HOSTS | default('web') }}"
  gather_facts: false
  become: yes
  tasks:
    - name: enable and start boinc-client
      systemd:
        name: boinc-client
        state: stopped
        enabled: false
