---
- hosts: ios
  gather_facts: no

  vars:

    log_servers:
      - logging 10.10.10.10
      - logging 10.10.10.11


  tasks:

  - name: "GET CONFIG"
    ios_command:
      commands:
        - show running-config full | include logging [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+
    register: log

  - name: RUN 'Set Logging'
    ios_config:
      commands: "{{ item }}"
    loop: "{{ log_servers }}"
    register: set_logging

  - debug: var=log.stdout_lines

  - name: RUN 'Remove Logging'
    ios_config:
      commands: "no {{ item }}"
    when:  "(log.stdout_lines[0][0] != '') and (item not in log_servers)"
    loop: "{{ log.stdout_lines[0] }}"
    register: remove_logging
