- name: public cloud not supported
  debug:
    msg: "there is no public cloud credentials for this install, installing dummy creds"

- name: add azure credential
  awx.awx.tower_credential:
    name: azure_credential
    description: Azure Service Principle
    organization: "Default"
    state: present
    kind: azure_rm
    subscription: "please replace me"
    tower_username: "{{ my_tower_username }}"
    tower_password: "{{ my_tower_password }}"
    tower_host: "{{ my_tower_host }}"
    validate_certs: false
